title: Random programming stuff
description: Thoughts, code, and obscure solutions to programming problems I stumble upon, especially the ones that made me spit blood to figure out. If it helped me, maybe it'll help you too.
license: |
  This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0).<br><br>
  To view a copy of this license, visit <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">https://creativecommons.org/licenses/by-nc-sa/4.0/</a> or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

excerpt_separator: "<!--more-->"

author:
  name: Borut J.
  email: me@borutj.anonaddy.me

remote_theme: jekyll/minima

minima:
  skin: dark
  show_excerpts: true
