title: Random programming stuff
description: Thoughts, code, and obscure solutions to programming problems I stumble upon, especially the ones that made me spit blood to figure out. If it helped me, maybe it'll help you too.

author:
  name: Borut J.
  email: me@borutj.anonaddy.me

theme: minima

minima:
  skin: dark
  show_excerpts: true
